class ValidatorError(Exception):
    """Raised when logical error happened in ``ResponseValidator``"""
    pass
